//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalSystem_Corona.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Sickness = new HashSet<Sickness>();
            this.Vaccination = new HashSet<Vaccination>();
        }
        [Display(Name = "Patient id")]
        public int patient_id { get; set; }


        [Required(ErrorMessage = "Required* ")]

        [Display(Name = "first name")]
        public string first_name { get; set; }

        [Required(ErrorMessage = "Required* ")]
        [Display(Name = "last name")]
        public string last_name { get; set; }

        [Required(ErrorMessage = "Required* ")]
        [Display(Name = "id number")]
        public Nullable<int> id_number { get; set; }

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> birthday { get; set; }
        public string city { get; set; }
        public string street { get; set; }

        [Display(Name = "building number")]

        public Nullable<int> building_number { get; set; }

        [Display(Name = "apartment number")]
        public Nullable<int> apartment_number { get; set; }
        public Nullable<int> landline { get; set; }

        [Required(ErrorMessage = "Required* ")]

        [Display(Name = "mobile phone")]
        public Nullable<int> mobile_phone { get; set; }
        public byte[] image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sickness> Sickness { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vaccination> Vaccination { get; set; }
    }
}
