//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalSystem_Corona.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sickness
    {

        [Display(Name = " sickness id")]

        public int sickness_id { get; set; }


        [Display(Name = "positive result")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> positive_result { get; set; }


        [Display(Name = "date of recovery")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> date_of_recovery { get; set; }


        [Display(Name = "patient id")]
        public Nullable<int> patient_id { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
